### ISSUE TITLE
Error run script : python training_sts.py

### ISSUE THREAD

**Issue by nugury55** [BM-K/KoSentenceBERT#1]
실행 환경
- Windows 10
- Anaconda : Python 3.7
- requirements.txt 설치 후 sentence_transformers, tokenizers, transformers 폴더 가상환경의 site-packages 폴더에 복사
- ETRI KorBERT 모델 및 토크나이저 root에 복사
- 실행 스크립트 : python training_sts.py
- 오류 내용
  -> ModuleNotFoundError: No module named 'tokenizers.tokenizers'
Traceback (most recent call last):
  File "training_sts.py", line 3, in <module>
    from sentence_transformers import SentenceTransformer,  SentencesDataset, LoggingHandler, losses, models, util
  File "D:\jhim\21.project\27.nlp\KoSentenceBERT\KoSentenceBERT\sentence_transformers\__init__.py", line 3, in <module>
    from .datasets import SentencesDataset, SentenceLabelDataset, ParallelSentencesDataset
  File "D:\jhim\21.project\27.nlp\KoSentenceBERT\KoSentenceBERT\sentence_transformers\datasets\__init__.py", line 1, in <module>
    from .sampler import *
  File "D:\jhim\21.project\27.nlp\KoSentenceBERT\KoSentenceBERT\sentence_transformers\datasets\sampler\__init__.py", line 1, in <module>
    from .LabelSampler import *
  File "D:\jhim\21.project\27.nlp\KoSentenceBERT\KoSentenceBERT\sentence_transformers\datasets\sampler\LabelSampler.py", line 6, in <module>
    from ...datasets import SentenceLabelDataset
  File "D:\jhim\21.project\27.nlp\KoSentenceBERT\KoSentenceBERT\sentence_transformers\datasets\SentenceLabelDataset.py", line 8, in <module>
    from .. import SentenceTransformer
  File "D:\jhim\21.project\27.nlp\KoSentenceBERT\KoSentenceBERT\sentence_transformers\SentenceTransformer.py", line 10, in <module>
    import transformers
  File "D:\jhim\21.project\27.nlp\KoSentenceBERT\KoSentenceBERT\transformers\__init__.py", line 55, in <module>
    from .data import (
  File "D:\jhim\21.project\27.nlp\KoSentenceBERT\KoSentenceBERT\transformers\data\__init__.py", line 6, in <module>
    from .processors import (
  File "D:\jhim\21.project\27.nlp\KoSentenceBERT\KoSentenceBERT\transformers\data\processors\__init__.py", line 6, in <module>
    from .squad import SquadExample, SquadFeatures, SquadV1Processor, SquadV2Processor, squad_convert_examples_to_features
  File "D:\jhim\21.project\27.nlp\KoSentenceBERT\KoSentenceBERT\transformers\data\processors\squad.py", line 11, in <module>
    from ...tokenization_bert import whitespace_tokenize
  File "D:\jhim\21.project\27.nlp\KoSentenceBERT\KoSentenceBERT\transformers\tokenization_bert.py", line 24, in <module>
    from tokenizers import BertWordPieceTokenizer
  File "D:\jhim\21.project\27.nlp\KoSentenceBERT\KoSentenceBERT\tokenizers\__init__.py", line 3, in <module>
    from .tokenizers import Tokenizer, Encoding, AddedToken
ModuleNotFoundError: No module named 'tokenizers.tokenizers'

가이드 대로 가상 환경에 개발 환경을 구축하였는데 훈련 시 오류가 발생합니다.
오류가 발생한 모듈은 conda list나 pip list로 확인 시 설치 되어 있는 것으로 나오는데요 실행 환경(Windows OS)가 문제일까요?

**Comment by nugury55** [comment]
requirements.txt의 transformers == 2.8.0을 수행하지 않고 git에 있는 transformers 폴더를 site-packages에 복사하면 위 문제는 해결 됩니다.

**Comment by nugury55** [comment]
...
